s/member/participant, and other light edits
bifurcation/mimi-arch pull request #10
Opened 2023-10-20 05:08 UTC by turt2live

See commits.

Fixes https://github.com/bifurcation/mimi-arch/issues/8
Fixes https://github.com/bifurcation/mimi-arch/issues/9
Fixes https://github.com/bifurcation/mimi-arch/issues/1

2023-10-20 05:08 UTC, turt2live commented on draft-barnes-mimi-arch.md
> -> if they have one or more clients joined.
This is removed because of formed consensus within the design team

2023-10-20 19:02 UTC, bifurcation requested changes

2023-10-20 19:02 UTC, bifurcation commented on draft-barnes-mimi-arch.md
> +are participants of the room.  There is exactly one _hub_ server for the room, which
I would use "participants in" vs. "participants of".

2023-10-20 19:02 UTC, bifurcation commented on draft-barnes-mimi-arch.md
> +users are _members_ of the end-to-end security state for the room.  The specific
The "while" here reads ambiguously -- I initially parsed it as meaning that a user is only a participant if they have clients joined.  Suggest the following rewrite:

```suggestion
For clarity, we use different words to express the inclusion of users and clients 
in a room.  Users are `participants` in a room; clients are `members` of the
end-to-end security state of the room.  The specific
```

2023-10-20 19:02 UTC, bifurcation commented on draft-barnes-mimi-arch.md
> +The collective membership of a group can change over time, via _add_ and _remove_
```suggestion
The participant list and client membership of a group can change over time, via _add_ and _remove_
```

2023-10-20 19:19 UTC, turt2live commented on draft-barnes-mimi-arch.md
> +are participants of the room.  There is exactly one _hub_ server for the room, which
```suggestion
are participants in the room.  There is exactly one _hub_ server for the room, which
```

2023-10-21 19:27 UTC, bifurcation approved these changes

2023-10-21 20:09 UTC, merged